### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by BFergerson** [Fengrui-Liu/StreamAD#7]
**Describe the bug**

My background is entirely JVM based so my apologies if it turns out I'm doing something dumb. Essentially, I'm trying to get a feel for this library before feeding it real data and it's occasionally throwing errors on a simple data stream. 

**To Reproduce**

1. Run the following code several times (5 times should be enough):
```python
import random

import numpy as np
from streamad.model import SpotDetector

model = SpotDetector()

if __name__ == '__main__':

    for lp in range(1000):
        score = model.fit_score(np.array([random.choice([0, 1])]))
        print("score: " + str(score))

```

**Expected behavior**

I'd expect it to give me a score between 0.0 and 1.0 for each loop.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3

**Package version (please complete the following information):**
 - Version: pypi 0.1.1

**Additional context**

Sometimes the output is:
```
score: 0.0
score: 0.0
...
```

Sometimes the output is:
```
score: None
score: None
...
```

With the error:
```
Traceback (most recent call last):
  File "/home/brandon/PycharmProjects/streamad/main.py", line 11, in <module>
    score = model.fit_score(np.array([random.choice([0, 1])]))
  File "/home/brandon/PycharmProjects/streamad/venv/lib/python3.8/site-packages/streamad/base/detector.py", line 59, in fit_score
    return self.fit(X).score(X)
  File "/home/brandon/PycharmProjects/streamad/venv/lib/python3.8/site-packages/streamad/model/spot_Detector.py", line 275, in fit
    self._init_drift(X)
  File "/home/brandon/PycharmProjects/streamad/venv/lib/python3.8/site-packages/streamad/model/spot_Detector.py", line 257, in _init_drift
    gamma, sigma, _ = self._grimshaw(side)
  File "/home/brandon/PycharmProjects/streamad/venv/lib/python3.8/site-packages/streamad/model/spot_Detector.py", line 66, in _grimshaw
    Ym = self.peaks[side].min()
  File "/home/brandon/PycharmProjects/streamad/venv/lib/python3.8/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by Fengrui-Liu** [comment]
@BFergerson Thanks for your help, this problem is caused by an unsafe divide operation. I have fixed it [here](https://github.com/Fengrui-Liu/StreamAD/commit/3266c28f74fda93efb1f011fd1cdfbdd8cd0e0e5#r76571774).

BTW, score `None` is Ok for the detector, it means that the detector learns the data distribution with a cold start, with no outputs.

----- 

FYI, normalized score has been implemented independently with [Thresholder](https://streamad.readthedocs.io/en/latest/api/streamad.process.html#post-process), you will see it in the next release.

---- 

Again, thanks for your help with this improvement. This project aims for studying and benchmarking, and strongly recommend you to have a wide test before deploying it on a production system.

**Comment by BFergerson** [comment]
@Fengrui-Liu, thanks for the quick fix. I can confirm it's working as expected now.

I know this goes beyond the scope of this issue but perhaps you could answer another question. I found your project via your comment on Apache SkyWalking about AIOps. You mention "change point detection" as something StreamAD could be considered for. Could it also be considered for "spike detection" as implemented by [IidSpikeEstimator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.timeseries.iidspikeestimator?view=ml-dotnet)? If so, would StreamAD need to add additional detectors are there already detectors that would be suitable for "adaptive kernel density estimation"?

**Comment by BFergerson** [comment]
Thanks for the suggestions. I did run into another issue though.

The following code:
```python
import numpy as np

from streamad.model import SpotDetector, KNNDetector
from streamad.process import TDigestThresholder

model = SpotDetector()

if __name__ == '__main__':

    model = TDigestThresholder(detector=KNNDetector())

    for x in range(500):
        score = model.fit_score(np.array([5]))
        print("score: " + str(score))

```

Produces this error:
```
Traceback (most recent call last):
  File "/home/brandon/PycharmProjects/StreamAD/test/main.py", line 13, in <module>
    score = model.fit_score(np.array([5]))
  File "/home/brandon/PycharmProjects/StreamAD/streamad/process/tdigest_Thresholder.py", line 50, in fit_score
    self.detector.fit_score(X)
  File "/home/brandon/PycharmProjects/StreamAD/streamad/base/detector.py", line 55, in fit_score
    score = self.fit(X).score(X)
  File "/home/brandon/PycharmProjects/StreamAD/streamad/model/KNN_Detector.py", line 45, in score
    dist = cdist(np.array([window]), self.buffer, metric="mahalanobis")[0]
  File "/home/brandon/PycharmProjects/StreamAD/venv/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2947, in cdist
    return cdist_fn(XA, XB, out=out, **kwargs)
  File "/home/brandon/PycharmProjects/StreamAD/venv/lib/python3.8/site-packages/scipy/spatial/distance.py", line 1664, in __call__
    XA, XB, typ, kwargs = _validate_cdist_input(
  File "/home/brandon/PycharmProjects/StreamAD/venv/lib/python3.8/site-packages/scipy/spatial/distance.py", line 206, in _validate_cdist_input
    kwargs = _validate_kwargs((XA, XB), mA + mB, n, **kwargs)
  File "/home/brandon/PycharmProjects/StreamAD/venv/lib/python3.8/site-packages/scipy/spatial/distance.py", line 247, in _validate_mahalanobis_kwargs
    VI = np.linalg.inv(CV).T.copy()
  File "<__array_function__ internals>", line 180, in inv
  File "/home/brandon/PycharmProjects/StreamAD/venv/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/brandon/PycharmProjects/StreamAD/venv/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

**Comment by Fengrui-Liu** [comment]
Fixed!
